// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: collector.proto

package com.sunshuo.grpc.jaeger;


public final class Collector {
  private Collector() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface PostSpansRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:jaeger.api_v2.PostSpansRequest)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>.jaeger.api_v2.Batch batch = 1 [(.gogoproto.nullable) = false];</code>
     * @return Whether the batch field is set.
     */
    boolean hasBatch();
    /**
     * <code>.jaeger.api_v2.Batch batch = 1 [(.gogoproto.nullable) = false];</code>
     * @return The batch.
     */
    Model.Batch getBatch();
  }
  /**
   * Protobuf type {@code jaeger.api_v2.PostSpansRequest}
   */
  public  static final class PostSpansRequest extends
      com.google.protobuf.GeneratedMessageLite<
          PostSpansRequest, PostSpansRequest.Builder> implements
      // @@protoc_insertion_point(message_implements:jaeger.api_v2.PostSpansRequest)
      PostSpansRequestOrBuilder {
    private PostSpansRequest() {
    }
    public static final int BATCH_FIELD_NUMBER = 1;
    private Model.Batch batch_;
    /**
     * <code>.jaeger.api_v2.Batch batch = 1 [(.gogoproto.nullable) = false];</code>
     */
    @Override
    public boolean hasBatch() {
      return batch_ != null;
    }
    /**
     * <code>.jaeger.api_v2.Batch batch = 1 [(.gogoproto.nullable) = false];</code>
     */
    @Override
    public Model.Batch getBatch() {
      return batch_ == null ? Model.Batch.getDefaultInstance() : batch_;
    }
    /**
     * <code>.jaeger.api_v2.Batch batch = 1 [(.gogoproto.nullable) = false];</code>
     */
    private void setBatch(Model.Batch value) {
      value.getClass();
      batch_ = value;
      }

    /**
     * <code>.jaeger.api_v2.Batch batch = 1 [(.gogoproto.nullable) = false];</code>
     */
    private void clearBatch() {  batch_ = null;

    }

    public static Collector.PostSpansRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Collector.PostSpansRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Collector.PostSpansRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Collector.PostSpansRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Collector.PostSpansRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Collector.PostSpansRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Collector.PostSpansRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static Collector.PostSpansRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static Collector.PostSpansRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static Collector.PostSpansRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static Collector.PostSpansRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static Collector.PostSpansRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(Collector.PostSpansRequest prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code jaeger.api_v2.PostSpansRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          Collector.PostSpansRequest, Builder> implements
        // @@protoc_insertion_point(builder_implements:jaeger.api_v2.PostSpansRequest)
        Collector.PostSpansRequestOrBuilder {
      // Construct using com.genshuixue.student.jaeger.Collector.PostSpansRequest.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>.jaeger.api_v2.Batch batch = 1 [(.gogoproto.nullable) = false];</code>
       */
      @Override
      public boolean hasBatch() {
        return instance.hasBatch();
      }
      /**
       * <code>.jaeger.api_v2.Batch batch = 1 [(.gogoproto.nullable) = false];</code>
       */
      @Override
      public Model.Batch getBatch() {
        return instance.getBatch();
      }
      /**
       * <code>.jaeger.api_v2.Batch batch = 1 [(.gogoproto.nullable) = false];</code>
       */
      public Builder setBatch(Model.Batch value) {
        copyOnWrite();
        instance.setBatch(value);
        return this;
        }


      /**
       * <code>.jaeger.api_v2.Batch batch = 1 [(.gogoproto.nullable) = false];</code>
       */
      public Builder clearBatch() {  copyOnWrite();
        instance.clearBatch();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:jaeger.api_v2.PostSpansRequest)
    }
    @Override
    @SuppressWarnings({"unchecked", "fallthrough"})
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new Collector.PostSpansRequest();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            Object[] objects = new Object[] {
              "batch_",
            };
            String info =
                "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0000\u0000\u0001\t";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<Collector.PostSpansRequest> parser = PARSER;
          if (parser == null) {
            synchronized (Collector.PostSpansRequest.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<Collector.PostSpansRequest>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:jaeger.api_v2.PostSpansRequest)
    private static final Collector.PostSpansRequest DEFAULT_INSTANCE;
    static {
      PostSpansRequest defaultInstance = new PostSpansRequest();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        PostSpansRequest.class, defaultInstance);
    }

    public static Collector.PostSpansRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<PostSpansRequest> PARSER;

    public static com.google.protobuf.Parser<PostSpansRequest> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface PostSpansResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:jaeger.api_v2.PostSpansResponse)
      com.google.protobuf.MessageLiteOrBuilder {
  }
  /**
   * Protobuf type {@code jaeger.api_v2.PostSpansResponse}
   */
  public  static final class PostSpansResponse extends
      com.google.protobuf.GeneratedMessageLite<
          PostSpansResponse, PostSpansResponse.Builder> implements
      // @@protoc_insertion_point(message_implements:jaeger.api_v2.PostSpansResponse)
      PostSpansResponseOrBuilder {
    private PostSpansResponse() {
    }
    public static Collector.PostSpansResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Collector.PostSpansResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Collector.PostSpansResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Collector.PostSpansResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Collector.PostSpansResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Collector.PostSpansResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Collector.PostSpansResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static Collector.PostSpansResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static Collector.PostSpansResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static Collector.PostSpansResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static Collector.PostSpansResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static Collector.PostSpansResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(Collector.PostSpansResponse prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code jaeger.api_v2.PostSpansResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          Collector.PostSpansResponse, Builder> implements
        // @@protoc_insertion_point(builder_implements:jaeger.api_v2.PostSpansResponse)
        Collector.PostSpansResponseOrBuilder {
      // Construct using com.genshuixue.student.jaeger.Collector.PostSpansResponse.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      // @@protoc_insertion_point(builder_scope:jaeger.api_v2.PostSpansResponse)
    }
    @Override
    @SuppressWarnings({"unchecked", "fallthrough"})
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new Collector.PostSpansResponse();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            Object[] objects = null;
            String info =
                "\u0000\u0000";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<Collector.PostSpansResponse> parser = PARSER;
          if (parser == null) {
            synchronized (Collector.PostSpansResponse.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<Collector.PostSpansResponse>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:jaeger.api_v2.PostSpansResponse)
    private static final Collector.PostSpansResponse DEFAULT_INSTANCE;
    static {
      PostSpansResponse defaultInstance = new PostSpansResponse();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        PostSpansResponse.class, defaultInstance);
    }

    public static Collector.PostSpansResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<PostSpansResponse> PARSER;

    public static com.google.protobuf.Parser<PostSpansResponse> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
